# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('nick_name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('blood_type', models.CharField(max_length=10)),
                ('team', models.IntegerField()),
                ('batch', models.CharField(max_length=100)),
                ('batch_no', models.IntegerField()),
                ('birthday', models.DateField()),
                ('english_name', models.CharField(max_length=50)),
                ('join_time', models.DateField()),
                ('link', models.CharField(max_length=300)),
                ('image_link', models.CharField(max_length=300)),
                ('hobby', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_valid', models.IntegerField()),
                ('constellation', models.CharField(max_length=50)),
                ('birth_place', models.CharField(max_length=50)),
                ('agency', models.CharField(max_length=50)),
                ('speciality', models.CharField(max_length=500)),
            ],
        ),
    ]
