# Generated by Django 4.1.7 on 2023-05-31 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("snh48", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transfer",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("detail", models.JSONField(verbose_name="变更详情")),
                (
                    "update_time",
                    models.DateTimeField(
                        blank=True,
                        default=models.DateTimeField(auto_now_add=True),
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "成员信息变更",
                "verbose_name_plural": "成员信息变更",
                "db_table": "transfer",
                "managed": False,
            },
        ),
    ]
