# Generated by Django 3.1.1 on 2020-09-19 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snh48', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiliBiliStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.IntegerField()),
                ('view', models.IntegerField()),
                ('danmaku', models.IntegerField()),
                ('reply', models.IntegerField()),
                ('favorite', models.IntegerField()),
                ('coin', models.IntegerField()),
                ('share', models.IntegerField()),
                ('update_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'bilibili_stat',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='unithistory',
            table='unit_history',
        ),
    ]
