# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snh48', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('num', models.IntegerField()),
            ],
            options={
                'db_table': 'unit',
                'managed': False,
            },
        ),
    ]
