# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-27 22:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snh48', '0002_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'performance_history',
                'managed': False,
            },
        ),
    ]
