# Generated by Django 4.1.7 on 2023-07-25 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("snh48", "0002_alter_performancesong_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="performancesongperformances",
            name="rank",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="performancesongperformances",
            name="song_type",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="performancesongperformances",
            name="performance",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="snh48.performance"
            ),
        ),
        migrations.AlterField(
            model_name="performancesongperformances",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="snh48.performancesong",
            ),
        ),
    ]
