# Generated by Django 4.2.19 on 2025-02-27 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snh48', '0003_performancesongperformances_rank_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenbatsuElection',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('order', models.IntegerField(unique=True)),
                ('hold_date', models.DateField()),
                ('slot', models.IntegerField()),
                ('theme', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': '青春盛典',
                'verbose_name_plural': '青春盛典',
                'db_table': 'senbatsu_election',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SenbatsuElectionDetail',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('order', models.IntegerField()),
                ('result_type', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('votes', models.FloatField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='snh48.memberinfo')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='snh48.team')),
            ],
            options={
                'verbose_name': '青春盛典详情',
                'verbose_name_plural': '青春盛典详情',
                'db_table': 'senbatsu_election_detail',
                'managed': True,
            },
        ),
    ]
